### ISSUE TITLE
Hardware with SIM-card support?

### ISSUE THREAD

**Issue by NitroNils** [unixsheikh/openbsd-router-guide#10]
There is no reference to SIM-card/4G/LTE on the site. Is there some hardware that supports it?

I guess on could fiddle about with mobile phones and use the urtwn-driver and such, or laptops that have a slot. Or use a data-SIM router to pick up the signals and transfer them to the OpenBSD router/firewall via cable.

**Comment by netstx** [comment]
@NitroNils OpenBSD has support for mobile network modems, you could try devices supported by [umb(4)](https://man.openbsd.org/umb.4) or [cdce(4)](https://man.openbsd.org/cdce.4) as examples - the man pages will typically have a list of supported devices, and you could search the mailing list or just the web in general for examples of specific devices folks have had success with.

I personally think using a 4G LTE gateway with an Ethernet hand-off is probably the "simplest" way, since you wouldn't have to worry about device/chip compatibility in most cases as long as the gateway has proper Ethernet and IP/TCP implementation.
